app/member/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField,\
    StringField, BooleanField, HiddenField
from wtforms.validators import DataRequired
from flask_admin.form.widgets import Select2Widget


class ApplyForLoanForm(FlaskForm):
    """Form for Apply Loan."""

    # amount = DecimalField(validators=[DataRequired()])
    amount = SelectField(validators=[DataRequired()],
                         choices=[], coerce=float, widget=Select2Widget())
    terms = SelectField(validators=[DataRequired()], choices=[], coerce=int,
                        widget=Select2Widget())
    # continue_1 = SubmitField('Continue', render_kw={"class_": "btn-primary"})


class BankDetailsForm(FlaskForm):
    """Form for Bank Details when applying for loan."""

    bank_name = SelectField(validators=[DataRequired()], choices=[],
                            coerce=int)
    account_number = StringField(validators=[DataRequired()])
    account_name = StringField(validators=[DataRequired()])
    save_account = BooleanField(default=True)
    # submit = SubmitField()


class MemberBankForm(FlaskForm):
    """Form for Member Bank when applying for loan."""

    member_bank_id = HiddenField()
    bank_name = SelectField(validators=[DataRequired()], choices=[],
                            coerce=int)
    account_number = StringField(validators=[DataRequired()])
    account_name = StringField(validators=[DataRequired()])
    submit = SubmitField('+Add account')

app/member/__init__.py
from flask import Blueprint

bp = Blueprint('member', __name__)

from app.member import routes

app/member/routes.py
from app.member import bp

from flask import flash, redirect, render_template, request,\
    url_for, abort
from flask_user import login_required
from app.user_models import User
from app.member.models import Service, AmortizationSchedule, Loan, Bank,\
    MemberBank, UserDetail
from .forms import ApplyForLoanForm, MemberBankForm
from datetime import datetime
from dateutil.relativedelta import relativedelta
from decimal import Decimal
from app import db


user = None
service = None
loan = None
amortization = []


def amortize_loan(amount, terms, interest_rate, date_filed):
    amortization = []
    prev_bal = amount
    due_date_1 = date_filed + relativedelta(months=1)
    due_date = due_date_1

    for i in range(1, terms + 1):
        if i == (terms):
            principal_am = prev_bal
        else:
            principal_am = round(Decimal(amount / terms), 2)
        interest_am = round(prev_bal * interest_rate * Decimal('0.01'),
                            2)
        am = AmortizationSchedule(
            due_date=due_date,
            previous_balance=prev_bal,
            principal=principal_am,
            interest=interest_am,
            ideal_balance=prev_bal - principal_am)
        amortization.append(am)
        prev_bal = am.ideal_balance
        due_date = due_date_1 + relativedelta(months=i)

    return amortization


@bp.route('/apply-for-loan/<int:user_id>/<int:service_id>',
          methods=['GET', 'POST'])
@bp.route('/apply-for-loan/<int:user_id>/<int:service_id>/<reload>',
          methods=['GET', 'POST'])
@login_required
def apply_for_loan(user_id, service_id, reload='0'):
    global user
    global service
    global loan
    global amortization

    # Load the user and service if coming from the Dashboard or Services
    #   or from the Checkout to ensure eligibility
    user = User.query.get(user_id)
    if not user.detail:
        return render_template('member/member_not_defined.html')
    member = UserDetail.query.filter_by(user_id=user_id).first()
    service = Service.query.get(service_id)

    balance = 5500
    process_fee = 250
    # default_loan_amount = 51000  # user.details.basic_salary * 0.8
    default_loan_amount = member.salary.salary
    default_loan_terms = service.max_term

    form = ApplyForLoanForm()
    form.terms.choices = [(x, str(x)) for x in
                          range(service.min_term, service.max_term + 1)]
    n = round(member.salary.salary, -3)
    form.amount.choices =\
        [(member.salary.salary, str(round(member.salary.salary, 0)))] +\
        [(x, str(x)) for x in range(int(n), 1000, -1000)]

    if request.form:
        form.amount.data = Decimal(request.form['amount'])
        form.terms.data = int(request.form['terms'])
    else:
        if (reload == '1') and loan:
            form.amount.data = loan.amount
            form.terms.data = loan.terms
        else:
            form.amount.data = default_loan_amount
            form.terms.data = default_loan_terms

    loan_amount = form.amount.data
    loan_terms = form.terms.data

    net_proceeds = loan_amount - balance - process_fee

    date_filed = datetime.now()

    amortization = amortize_loan(loan_amount,
                                 loan_terms,
                                 service.interest_rate,
                                 date_filed)
    loan = Loan(
        user_id=user.id,
        service_id=service.id,
        date_filed=date_filed,
        amount=loan_amount,
        terms=loan_terms,
        interest_rate=service.interest_rate,
        previous_balance=balance,
        processing_fee=process_fee,
        net_proceeds=net_proceeds,
        first_due_date=amortization[0].due_date,
        last_due_date=amortization[-1].due_date,
        status='submitted')

    if form.validate_on_submit():
        if 'continue' in request.form:
            # session['back_url'] = request.url

            return redirect(url_for('member.apply_for_loan_checkout'))

    return render_template('member/apply_for_loan.html',
                           user=user,
                           service=service,
                           loan=loan,
                           form=form,
                           amortization=amortization)


@bp.route('/apply-for-loan-checkout/',
          methods=['GET', 'POST'])
@login_required
def apply_for_loan_checkout():
    global user
    global service
    global loan
    global amortization

    if not loan:
        flash("""You have been redirected because the page you are trying
            to access is no longer valid.""", 'info')
        return redirect(url_for('main.dashboard'))

    banks = Bank.all_active()

    form = MemberBankForm()
    form.bank_name.choices = [(bank.id, bank.name) for bank in banks]

    if not request.form:
        member_banks = MemberBank.query.filter_by(user_id=user.id).all()
        if member_banks:
            form.member_bank_id.data = member_banks[0].id
            form.account_number.data = member_banks[0].account_number
            form.account_name.data = member_banks[0].account_name
            form.bank_name.data = member_banks[0].bank.name
        else:
            form.account_number.data = ''
            form.account_name.data = user.detail.full_name

    if request.method == 'POST':

        if 'back' in request.form:
            return redirect(url_for('member.apply_for_loan',
                                    user_id=user.id,
                                    service_id=service.id,
                                    reload='1'))

        if form.validate_on_submit():

            mb_id = form.member_bank_id.data
            mb = MemberBank(
                id=mb_id,
                user_id=user.id,
                bank_id=form.bank_name.data,
                account_number=form.account_number.data,
                account_name=form.account_name.data)

            if mb.is_unique_record():
                mb.id = None
                db.session.add(mb)
            db.session.flush()
            loan.memberbank_id = mb.id
            db.session.add(loan)
            # TODO: continue here: account edit when only account name changed
            try:
                db.session.commit()
                user = None
                service = None
                loan = None
                amortization = []
                return render_template('member/apply_for_loan_success.html')
            except Exception:
                raise
                flash('Error occurred.', 'error')
                db.session.rollback()

    return render_template('member/apply_for_loan_checkout.html',
                           user=user,
                           service=service,
                           loan=loan,
                           amortization=amortization,
                           member_banks=member_banks,
                           form=form)


@bp.route('/loans/<int:user_id>')
@login_required
def loans(user_id):
    loans = Loan.query.filter_by(user_id=user_id)\
        .order_by(Loan.date_filed.desc()).all()

    return render_template('member/loans.html', loans=loans)


@bp.route('/loan/<int:loan_id>')
@login_required
def loan(loan_id):
    loan = Loan.query.filter_by(id=loan_id).first()
    if not loan:
        abort(404)

    return render_template('member/loan.html', loan=loan)


@bp.route('/contributions/<int:user_id>')
@login_required
def contributions(user_id):
    c = [
        [2010, 4360.01, 8720.02, 13080.03],
        [2011, 4862.12, 9724.24, 14586.36],
        ['', '', '<b>Total</b>', 27666.39]
    ]
    return render_template('member/contributions.html', contributions=c)


@bp.route('/contributions/<int:user_id>/<int:year>')
@login_required
def contributions_by_year(user_id, year):
    c = [
        ['1/20/2010', 'Isabela PO', 'Contribution', 421.56, '1/1/2010'],
        ['1/20/2010', 'Isabela PO', 'Government Share', 843.12, '1/1/2010'],
        ['2/20/2010', 'Isabela PO', 'Contribution', 421.56, '2/1/2010'],
        ['2/20/2010', 'Isabela PO', 'Government Share', 843.12, '2/1/2010'],
    ]
    return render_template(
        'member/contributions_by_year.html', contributions=c, year=year)


@bp.route('/services')
@login_required
def services():
    services = Service.query.order_by(Service.id).all()
    return render_template(
        'member/services.html', services=services)

app/templates/member/apply_for_loan.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{# admin/lib.html is for the select2 widget #}
{# {% import 'admin/lib.html' as lib with context %} #}

{% set title = "Apply for Loan" %}

{% block title %}
{{ title }}
{% endblock %}

{% block head %}
  {{ super() }}
  {# {{ lib.form_css() }} #}

  
  <link href="/admin/static/vendor/select2/select2.css?v=3.5.2" rel="stylesheet">
  <link href="/admin/static/vendor/select2/select2-bootstrap3.css?v=1.4.6" rel="stylesheet">
{% endblock %}

{% block main_content %}

<div class="col-sm-12 ">
  <h3>{{ title }}</h3>
  <br>

<div class="row">
    <div class="col-lg-4 col-md-5">
        <h4 class="h4-gray">Loan details</h4>

        <table class="table-condensed">
            <tbody>
                <tr>
                    <td align="right">For:</td>
                    <td><b>{{ user.detail.full_name }}</b></td>
                </tr>
                <tr>
                    <td align="right" valign="top">Loan Type:</td>
                    <td><b>{{ service.name }}</b><br></td>
                </tr>
                <tr>
                    <td align="right">Interest Rate:</td>
                    <td><b>{{ service.interest_rate }}</b></td>
                </tr>

                <form action="" method="POST">
                    {{ form.csrf_token() }}
                    <tr>
                        <td align="right">Amount:</td>
                        <td><select class="form-control" id="amount" name="amount">
                            {% for i in form.amount.choices %}
                                <option value={{ i[0] }} {% if i[0] == form.amount.data%}selected{% endif %}>{{ i[1] }}</option>
                            {% endfor %}
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td align="right">Terms:</td>
                        <td><select class="form-control" id="terms" name="terms">
                            {% for i in form.terms.choices %}
                                <option value={{ i[0] }} {% if i[0] == form.terms.data%}selected{% endif %}>{{ i[1] }}
                                </option>
                            {% endfor %}
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td style="padding-left: 20px;">
                            <div class="row">
                                <input type="submit" class="btn btn-primary" name="continue" value="Continue" formaction="{{ form.submit }}">
                                <input type="submit" class="btn btn-default" name="recalc" value="Re-calculate" formaction="{{ form.submit }}">
                            </div>
                        </td>
                    </tr>
                </form>

            </tbody>
        </table>

        <h4 class="h4-gray">Adjustments</h4>
        <table class="table-condensed">
            <tbody>
                <tr>
                    <td align="right">Balance:</td>
                    <td align="right">{{ loan.previous_balance|money }}</td>
                </tr>
                <tr>
                    <td align="right">Processing Fee:</td>
                    <td align="right">{{ loan.processing_fee|money }}</td>
                </tr>
                <tr>
                    <td align="right">Net Proceeds:</td>
                    <td align="right"><font size="+1">{{ loan.net_proceeds|money }}</font></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="col-lg-6 col-md-6">
    <h4 class="h4-gray">Amortization Schedule</h4>
    <table class="table-condensed table-striped table-responsive">
        <thead>
            <tr>
                <th>No.</th>
                <th>Due Date</th>
                <th>Principal</th>
                <th>Interest</th>
                <th>Total</th>
                <th>Ideal Balance</th>
            </tr>
        </thead>
        <tbody>
            {% for am in amortization %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ am.due_date | date }}</td>
                <td align="right">{{ am.principal | money }}</td>
                <td align="right">{{ am.interest | money }}</td>
                <td align="right" style="background-color : lightgray;">{{ (am.principal + am.interest) | money }}</td>
                <td align="right">{{ am.ideal_balance | money }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

</div>

{% endblock %}

{% block scripts %}
{{ super() }}
    <script src="/admin/static/vendor/select2/select2.min.js?v=3.5.2" type="text/javascript"></script>
    <script type="text/javascript">
        $("#terms").select2();
    </script>
    <script type="text/javascript">
        $("#amount").select2();
    </script>

{% endblock %}

app/templates/member/apply_for_loan_checkout.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "layout.html" %}

{% set title = "Apply for Loan" %}

{% block title %}
{{ title }}
{% endblock %}

{% block head %}
	{{ super() }}
	<style>
		input.left-indent {
			margin-left: 40px;
		}
		label.plain {
			font-weight: normal;
		}
	</style>
{% endblock %}

{% block main_content %}

<div class="col-sm-12 ">
  <h3>{{ title }}</h3>
  <br>
  
  <div class="row">
  	<div class="col-sm-6 col-md-6 col-lg-6">

  	{% if member_banks %}
    <h4 class="h4-gray">Previous bank accounts</h4>
    <small>
	    {% for mb in member_banks %}
	    	<input class="left-indent" type="radio" id="mb{{ mb.id }}" name="member_bank" value="{{mb.account_number}}" 
	    		onclick="UpdateInput('{{mb.bank.id}}','{{mb.account_number}}','{{mb.account_name}}');">
	    	<label class="plain" for="mb{{ mb.id }}">{{ mb.account_number }}, {{ mb.bank.short_name }}, {{ mb.account_name|truncate(15, True) }}</label>
	    	<br>
	    {% endfor %}
    </small>
    {% endif %}

    <h4 class="h4-gray">Bank details for this loan</h4>

		<table class="table-condensed">
			<tbody>
				<form action="" method="POST">
					{{ form.csrf_token() }}
					{{ form.member_bank_id }}
					<tr>
						<td align="right">Bank Name:</td>
						<td><select class="form-control" id="bank_name" name="bank_name">
							{% for i in form.bank_name.choices %}
								<option value={{ i[0] }} {% if i[0] == form.bank_name.data%}selected{% endif %}>{{ i[1] }}
								</option>
							{% endfor %}
							</select>
						</td>
					</tr>
					<tr>
						<td align="right">Account&nbsp;Number:</td>
						<td><input type="text" class="form-control" id="account_number" name="account_number" required value="{{ form.account_number.data }}">
						</td>
					</tr>
					<tr>
						<td align="right">Account&nbsp;Name:</td>
						<td><input type="text" class="form-control" id="account_name" name="account_name" required value="{{ form.account_name.data }}">
						</td>
					</tr>{# 
					<tr>
						<td align="right">Save&nbsp;Account:</td>
						<td><input type="checkbox" style="width:20px; height:20px;" {% if form.save_account.data %}checked{% endif %} id="save_account" name="save_account" value="{{ form.save_account.data }}">
						</td>
					</tr> #}
					<tr>
						<td></td>
            <td style="padding-left: 20px;">
              <div class="row">
                <input type="submit" class="btn btn-primary" name="submit" value="Submit">
                <input type="submit" formnovalidate class="btn btn-default" name="back" value="Back">
              </div>
            </td>
					</tr>
				</form>
			</tbody>
		</table>
		<br>
		</div>

		<div class="col-sm-6 col-md-6 col-lg-6">
			<div class="panel panel-default">
				<div class="panel-body">
				<small><small>
					<b>Loan Details:</b>
					<br>
					<table class="table-condensed">
						<tr>
							<td width="100px;">
								For:<br>
								Loan Type:<br>
								Amount:<br>
								Terms:
							</td>
							<td>{{ user.detail.full_name }}<br>
								{{ service.name }}<br>
								{{ loan.amount|money }}<br>
								{{ loan.terms }} month{{loan.terms|pluralize }}
							</td>
						</tr>
					</table>
					<b>Adjustments:</b>
					<br>
					<table class="table-condensed">
						<tr>
							<td width="100px;">Previous Balance:<br>
								Processing Fee:<br>
								Net Proceeds:
							</td>
							<td align="right">{{ loan.previous_balance|money }}<br>
								{{ loan.processing_fee|money }}<br>
								{{ loan.net_proceeds|money }}
							</td>
						</tr>
					</table>
					<b>Amortization:</b>
					<br>
					<table class="table-condensed">
						<thead>
							<th>No.</th>
							<th>Due date</th>
							<th>Principal</th>
							<th>Interest</th>
							<th>Total</th>
							<th>Ideal Balance</th>
						</thead>
				        <tbody>
				            {% for am in amortization %}
				            <tr>
				                <td>{{ loop.index }}</td>
				                <td>{{ am.due_date | date }}</td>
				                <td align="right">{{ am.principal | money }}</td>
				                <td align="right">{{ am.interest | money }}</td>
				                <td align="right" style="background-color : lightgray;">{{ (am.principal + am.interest) | money }}</td>
				                <td align="right">{{ am.ideal_balance | money }}</td>
				            </tr>
				            {% endfor %}
				        </tbody>
					</table>
				</small></small>
				</div>
			</div>

		</div>
  </div>

</div>

{% endblock %}

{% block scripts %}
  {{ super() }}
  <script>
	function UpdateInput(bank_name, acct_no, acct_name)
	{
		console.log(bank_name);
		document.getElementById('bank_name').value = bank_name;
	  document.getElementById('account_number').value = acct_no;
	  document.getElementById('account_name').value = acct_name;
	}
  </script>
{% endblock %}

app/templates/member/apply_for_loan_success.html
{% extends "layout.html" %}

{% set title = "Application successful." %}

{% block title %}
{{ config.USER_APP_NAME }}
{% endblock %}

{% block main_content %}

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-7 ">
  <h3>{{ title }}</h3>
  <br>

  Your loan application has been submitted successfully for processing.
  <br>
  You will receive an email shortly to confirm this action.
  <br>
  <br>
  <a href="{{ url_for('main.dashboard') }}">
    <input type="button" class="btn btn-primary" name=ok value="Ok">
	</a>

</div>

{% endblock %}

app/templates/member/contributions.html
{% extends "layout.html" %}

{% set title = "Your Contributions" %}

{% block title %}
Contributions
{% endblock %}

{% block main_content %}

<div class="col-sm-10 col-md-8 col-lg-6 ">
  <h3>{{ title }}</h3>
  <br>

  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Year</th>
        <th class="text-right">Member Share</th>
        <th class="text-right">Employer Share</th>
        <th class="text-right">Total</th>
      </tr>
    </thead>
    <tbody>
      {% for c in contributions %}
        <tr>
          <td><a href="{{ url_for('member.contributions_by_year', user_id=current_user.id, year=c[0]|int) }}">{{ c[0] }}</a></td>
          <td align="right">{{ c[1]|money if c[1] is float else c[1] }}</td>
          <td align="right">{{ c[2]|money if c[2] is float else c[2]|safe }}</td>
          <td align="right">{{ c[3]|money if c[3] is float else c[3] }}</td>

        </tr>
        {% endfor %}

    </tbody>
  </table>
</div>

{% endblock %}

app/templates/member/contributions_by_year.html
{% extends "layout.html" %}

{% set title = "Contributions" %}

{% block title %}
{{ title }} : {{ year }}
{% endblock %}

{% block main_content %}

<div class="col-sm-10 col-md-8 col-lg-6 ">
  <ol class="breadcrumb">
    <li><a href="{{ url_for('member.contributions', user_id=current_user.id) }}">Contributions</a></li>
    <li class="active">{{ year }}</li>
  </ol>
  <h3>{{ title }} : {{ year }}</h3>
  <br>

  <div class="table-responsive">
  <table class="table table-condensed table-striped">
    <thead>
      <tr>
        <th>Transaction Date</th>
        <th>Branch</th>
        <th>Transaction Type</th>
        <th class="text-right">Amount</th>
        <th>Date Paid</th>
      </tr>
    </thead>
    <tbody>
      {% for c in contributions %}
        <tr>
          <td>{{ c[0] }}</td>
          <td>{{ c[1] }}</td>
          <td>{{ c[2] }}</td>
          <td align="right">{{ c[3]|money }}</td>
          <td>{{ c[4] }}</td>
        </tr>
        {% endfor %}

    </tbody>
  </table>
  </div>
</div>

{% endblock %}

app/templates/member/loan.html
{% extends "layout.html" %}

{% set title = 'Loan ' ~ loan.id %}

{% block title %}
{{ title }}
{% endblock %}

{% block styles %}
  {{ super() }}
  <style>
  	.table td.fit {
  		white-space: nowrap;
  		width: 1px;
  	}
  </style>
{% endblock %}

{% block main_content %}

<div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 ">
	<ol class="breadcrumb">
		<li><a href="{{ url_for('member.loans', user_id=current_user.id) }}">Loans</a></li>
		<li class="active">{{ title }}</li>
	</ol>
	<h3>{{ loan.service.name + " / " + loan.user.detail.full_name }}</h3>
	<br>

	{% if loan %}

		{# <div class="col-sm-6 col-md-6 col-lg-6"> #}
			<div class="panel panel-default">
				<div class="panel-body">
					<b>Loan Details:</b>
					<br>
					<table class="table-condensed table">
						<tr>
							<td style="min-width: 100px;">Borrower:</td>
							<td>{{ loan.user.detail.full_name }}</td>
						</tr>
						<tr>
							<td>Loan Type:</td>
							<td>{{ loan.service.name }}</td>
						</tr>
						<tr>
							<td>Amount:</td>
							<td>{{ loan.amount|money }}</td>
						</tr>
						<tr>
							<td>Terms:</td>
							<td>{{ loan.terms }} month{{loan.terms|pluralize}}</td>
						</tr>{# 
					</table>

					<b>Adjustments:</b>
					<br>
					<table class="table-condensed1 "> #}
						<tr>
							<td style="min-width: 200px;">Previous Balance:</td>
							<td>{{ loan.previous_balance|money }}</td>
						</tr>
						<tr>
							<td>Processing Fee:</td>
							<td>{{ loan.processing_fee|money }}</td>
						</tr>
						<tr>
							<td>Net Proceeds:</td>
							<td>{{ loan.net_proceeds|money }}</td>
						</tr>
					</table>
					<b>Amortization:</b>
					<br>
					<table class="table-condensed">
						<thead>
							<th>No.</th>
							<th>Due date</th>
							<th>Principal</th>
							<th>Interest</th>
							<th>Total</th>
							<th>Ideal Balance</th>
						</thead>
				        <tbody>
				            {% for am in amortization %}
				            <tr>
				                <td>{{ loop.index }}</td>
				                <td>{{ am.due_date | date }}</td>
				                <td align="right">{{ am.principal | money }}</td>
				                <td align="right">{{ am.interest | money }}</td>
				                <td align="right" style="background-color : lightgray;">{{ (am.principal + am.interest) | money }}</td>
				                <td align="right">{{ am.ideal_balance | money }}</td>
				            </tr>
				            {% endfor %}
				        </tbody>
					</table>
				</div>
			</div>

		{# </div> #}

	{% endif %}

</div>

{% endblock %}

app/templates/member/loans.html
{% extends "layout.html" %}

{% set title = "Loans" %}

{% block title %}
{{ title }}
{% endblock %}

{% block main_content %}

<div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 ">
  <h1>{{ title }}</h1>
  <br>

    {% if loans %}
        <table class="table table-condensed table-striped">
            <thead>
                <th>Date</th>
                <th>Loan Type</th>
                <th>Status</th>
                <th>Principal</th>
                <th>Deductions</th>
                <th>Net Proceeds</th>
                <th>Payments</th>
                <th>Balance</th>
                <th></th>
            </thead>
            <tbody>
                {% for loan in loans %}
                <tr>
                    <td>
                        <a href="{{ url_for('member.loan', loan_id=loan.id) }}">
                            {{ loan.date_filed|date }}
                        </a>
                    </td>
                    <td>{{ loan.service.name }}</td>
                    <td>Status</td>
                    <td>{{ loan.amount|money }}</td>
                    <td>{{ (loan.previous_balance + loan.processing_fee)|money }}</td>
                    <td>{{ loan.net_proceeds|money }}</td>
                    <td>Payments</td>
                    <td>Balance</td>
                    <td>{{ loan.date_filed|days_ago }}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{{ url_for('member.contributions', user_id=current_user.id) }}" style="float: right;">
            see more... (TODO:)
        </a>
    {% else %}
        You have no loan applications.
        <a href="{{ url_for('member.services') }}" style="float: right;">apply for loan...</a>
    {% endif %}

</div>

{% endblock %}

app/templates/member/member_not_defined.html
{% extends "layout.html" %}

{% set title = "Member details not defined." %}

{% block title %}
{{ config.USER_APP_NAME }}
{% endblock %}

{% block main_content %}

<div class="col-sm-7 col-md-6 col-lg-5 ">
  <h3>{{ title }}</h3>
  <br>

  Please contact your system administrator.

</div>

{% endblock %}

app/templates/member/services.html
{% extends "layout.html" %}

{% set title = "Services" %}

{% block title %}
{{ title }}
{% endblock %}

{% block main_content %}

<div class="col-sm-7 col-md-6 col-lg-6 ">
  <h3>{{ title }}</h3>
  <br>

  {# <div class="panel panel-default"> #}

    {% for service in services %}{#
      <b>{{ s.name }}</b>
      <br>
      {{ s.description }}
      <br>
      <br> #}


      <big><strong>{{ service.name }}</strong></big><br>
      {% set s = service.description.split('\n') %}
      {# <small> #}
      {% for l in s %}
      {{ l }}<br>
      {% endfor %}
      {# </small> #}
      <a href="{{ url_for('member.apply_for_loan', user_id=current_user.id, service_id=service.id) }}">
        <input type='button' class="btn btn-primary btn-md" value='Apply now'>
      </a>
      <br>
      <br>

    {% endfor %}

  {# </div> #}

</div>

{% endblock %}